server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:  #thymeleaf做了缓存，我们应关掉
    cache: false
  rabbitmq:
      host: 192.168.184.130
      username: leyou
      password: leyou
      virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

